---
title: "blog structure"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Post 1: for beginners

### The essentials:
- Installing xaringan - done

- Making slides - done

- Types of slide: usual and inverse - done

- Alignment - ongoing

- Adding images - done
  - background image
  - markdown images
  - html

- Adding icons and emoji (fontawesome and emo packages)

- Highlighting code

- YAML explanations: what does it mean?

- Built in formatting: swapping to metropolis or rladies themes. mention xariningthemer

- Built in formatting: changing code block theme



### Small tweaks

- Changing to widescreen

- Getting rid of the first slide

- Changing the way slide numbers appear

- Getting rid of the slide numbers ("" option)

- Click to advance slides



### Presenting

- Clone and presenter mode

- if this happens, no panic; just wait




### Making your own template

- Remembering these YAML instructions and where exactly to put them can be a challenge. If you have a set of preferences, --> template



<br>
<hr>
<br>

# Post 2: Making it your own

Adding your own CSS to the mix


### Modifying existing CSS classes

- Fonts

- Font colours

- Background colours

- Inline code

- Highlighting code

- Code chunks

- Bigger slide area

- Fonts bigger or smaller


### Making new CSS classes

- Handwritten example

- Making a third type of slide beyond normal and inverse



### Layouts? or keep for third one?








General advice: you see something you like -> go and inspect how they have done it.

- Folder structure

- Inspecting other people's xaringans... see Julia Silge, Jennifer Thompson